[versions]
agp = "8.8.0-alpha09"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.10.01"
openai-client-bom = "3.8.2"
retrofit = "2.11.0"
kotlinxDatetime = "0.6.1"
generativeai = "0.9.0"
secretsGradlePlugin = "2.0.1"
datastore = "1.1.1"
ratingbar = "1.3.12"
picasso = "2.71828"
constraintlayoutCompose = "1.1.0"
composeWebview = "0.33.6"
mdparserkitcore = "1.0.1"
dotlottieAndroid = "0.5.0"
emojipicker = "1.5.0"
emoji2ViewsHelper = "1.5.0"
documentfile = "1.0.1"
commonsIo = "+"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version = "1.7.5" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-text-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version = "1.7.5" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.7.5" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
openai-client-bom = { group = "com.aallam.openai", name = "openai-client-bom", version.ref = "openai-client-bom" }
openai-client = { group = "com.aallam.openai", name = "openai-client" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "retrofit" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
generativeai = { group = "ir.saltech.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
ratingbar-compose = { group = "com.github.a914-gowtham", name = "compose-ratingbar", version.ref="ratingbar" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
compose-webview = { group = "io.github.kevinnzou", name = "compose-webview", version.ref = "composeWebview" }
mdparserkitcore = { group = "io.github.dakshsemwal", name = "mdparserkitcore", version.ref = "mdparserkitcore" }
dotlottie-android = { group = "com.github.LottieFiles", name = "dotlottie-android", version.ref = "dotlottieAndroid" }
androidx-emojipicker = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emojipicker" }
androidx-emoji2-views-helper = { group = "androidx.emoji2", name = "emoji2-views-helper", version.ref = "emoji2ViewsHelper" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }


